using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class FKey
{
    public readonly static int U1 = 0;
    public readonly static int U2 = 1;
    public readonly static int U3 = 2;
    public readonly static int U4 = 3;
    public readonly static int U5 = 4;
    public readonly static int U6 = 5;
    public readonly static int U7 = 6;
    public readonly static int U8 = 7;
    public readonly static int U9 = 8;
    public readonly static int R1 = 9;
    public readonly static int R2 = 10;
    public readonly static int R3 = 11;
    public readonly static int R4 = 12;
    public readonly static int R5 = 13;
    public readonly static int R6 = 14;
    public readonly static int R7 = 15;
    public readonly static int R8 = 16;
    public readonly static int R9 = 17;
    public readonly static int F1 = 18;
    public readonly static int F2 = 19;
    public readonly static int F3 = 20;
    public readonly static int F4 = 21;
    public readonly static int F5 = 22;
    public readonly static int F6 = 23;
    public readonly static int F7 = 24;
    public readonly static int F8 = 25;
    public readonly static int F9 = 26;
    public readonly static int D1 = 27;
    public readonly static int D2 = 28;
    public readonly static int D3 = 29;
    public readonly static int D4 = 30;
    public readonly static int D5 = 31;
    public readonly static int D6 = 32;
    public readonly static int D7 = 33;
    public readonly static int D8 = 34;
    public readonly static int D9 = 35;
    public readonly static int L1 = 36;
    public readonly static int L2 = 37;
    public readonly static int L3 = 38;
    public readonly static int L4 = 39;
    public readonly static int L5 = 40;
    public readonly static int L6 = 41;
    public readonly static int L7 = 42;
    public readonly static int L8 = 43;
    public readonly static int L9 = 44;
    public readonly static int B1 = 45;
    public readonly static int B2 = 46;
    public readonly static int B3 = 47;
    public readonly static int B4 = 48;
    public readonly static int B5 = 49;
    public readonly static int B6 = 50;
    public readonly static int B7 = 51;
    public readonly static int B8 = 52;
    public readonly static int B9 = 53;
}
